### ISSUE TITLE
Allow default prompt.

### ISSUE THREAD

**Issue by alpipego** [MachatoApp/machato#100]
I would like to be able to set a default system prompt for all new conversations.

**Comment by FliiFe** [comment]
If I understand correctly, this is already possible at the bottom of the first pane in the settings window (`Default system prompt`)

![CleanShot 2024-05-15 at 11 04 07@2x](https://github.com/MachatoApp/machato/assets/8740385/c367c1d2-3b72-44c1-9014-839817f41921)

**Comment by alpipego** [comment]
OMG 🤦‍♂️ Thank you and sorry for that.
