### ISSUE TITLE
Add latest OpenAI models

### ISSUE THREAD

**Issue by Tafkas** [MachatoApp/machato#97]
Add the latest OpenAI models

- [GPT-4 Turbo and GPT-4](https://platform.openai.com/docs/models/gpt-4-turbo-and-gpt-4)
    - gpt-4-turbo
    - gpt-4-turbo-2024-04-09
- [GPT-3.5 Turbo](https://platform.openai.com/docs/models/gpt-3-5-turbo)
   - gpt-3.5-turbo 
   - gpt-3.5-turbo-0125

**Comment by FliiFe** [comment]
I've added those models a while ago, sorry I didn't see this issue! This is fixed in a48f38d4716bc76d0f63079bd37d7c07a85a613c
